project:
  type: website
  output-dir: docs
website:
  title: "Evelyn Tsang"
  favicon: images/icon-color.png
  navbar:
    title: false
    logo: images/icon-color.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projectpage.qmd
        text: My Projects
      - href: cookbook.qmd
        text: What's Cooking?
      - href: travel.qmd
        text: Travel Log
      - href: CV.qmd
        text: My CV
  page-footer: 
    background: light # or 'dark'
    left: Copyright 2025, Evelyn Tsang
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    #/disabled/respect-user-color-scheme: true
    #honors the user's operating system or browser preference for light or dark mode
    theme: styles.scss
    mainfont: Sono
      #/disabled/light: litera
      #/disabled/dark: solar
    toc: true
    page-layout: full

editor: visual

