project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Tsang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projectpage.qmd
      - cookbook.qmd
#setting theme
format:
  html:
    respect-user-color-scheme: true
    #honors the user's operating system or browser preference for light or dark mode
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

