project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Tsang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projectpage.qmd
      - cookbook.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

