project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Tsang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projectpage.qmd
        text: My Projects
      - href: cookbook.qmd
        text: What's Cooking?
      - href: travel.qmd
        text: Travel Log
      - href: CV.qmd
        text: My CV
#setting theme
format:
  html:
    respect-user-color-scheme: true
    #honors the user's operating system or browser preference for light or dark mode
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

